### ISSUE TITLE
Koder doesn't like big files

### ISSUE THREAD

**Issue by humdingerb** [KapiX/Koder#100] opened 2019-01-09 17:04 UTC
I have an almost 2 MiB big "hosts" file that Koder doesn't deal well with. It takes a second or two to open and then editing or even scrolling or placing the cursor pegs one core in the window thread.

I can upload the hosts file, if needed.

**Comment by KapiX** [comment] 2019-01-13 11:04
Do you have whitespace highlight enabled? Is it better if you disable it?

**Comment by humdingerb** [comment] 2019-01-13 13:36
Yep, that's exactly it. Without highlighting trailing whitespace, editing and scrolling is fast as ever.

**Comment by KapiX** [comment] 2019-01-13 14:51
Dupe of #47.

**Closed by KapiX** 2019-01-13 14:51 UTC
