### ISSUE TITLE
Add status bar

### ISSUE THREAD

**Issue by anevilyak** [KapiX/Koder#52] opened 2018-08-22 01:30 UTC
It would be nice to have a status bar indicating some helpful details such as the current line/column of the caret, detected file format (or active syntax highlighter), whether the document has unsaved changes, and possibly items that might impact editing such as the state of caps lock.

**Comment by KapiX** [comment] 2018-08-22 04:50
Duplicate of #30.

**Closed by KapiX** 2018-08-22 04:50 UTC
