### ISSUE TITLE
Preferences window is jumpy

### ISSUE THREAD

**Issue by diversys** [KapiX/Koder#66] opened 2018-10-16 19:42 UTC
Clicking some options like `Mark overly long lines` and `Highlight current line` makes controls jump a bit. I see that the window becomes taller for a split of a second which then goes back.

**Comment by KapiX** [comment] 2018-10-22 18:35
I couldn't reproduce the issue with `Highlight current line`, but `Mark overly long lines` indeed exhibits this behavior. However, I don't think there is anything I can do about it: I'm simply using layout kit, and in case of this window I'm not even doing any weird shenanigans (as is the case with StatusView in main window).
The issue is probably caused by disabled TextControl having different height than enabled one. Switching between the states triggers relayouting.
Summarizing: looks like an Haiku issue. Closing as invalid.

**Closed by KapiX** 2018-10-22 18:35 UTC
